[features]
seeds = false
skip-lint = false
[programs.localnet]
nightfury = "4Wv3EabUK62p1TvavGi67An7JTLBy5sxJ9PAFbLkE1vQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nilz3ro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
